package dev.pnptracker.data.database.entity

import androidx.room3.ColumnInfo
import androidx.room3.Entity
import androidx.room3.ForeignKey
import androidx.room3.Index
import androidx.room3.PrimaryKey
import dev.pnptracker.domain.model.EntityId
import dev.pnptracker.domain.model.ProductionStage
import dev.pnptracker.domain.model.ProgressEventKind
import kotlin.time.Instant

/**
 * One recorded movement of a task's progress.
 *
 * The history is append only. Nothing updates a row here and nothing deletes
 * one: PLAN 6.3 keeps the total ever reported failed for the life of the task,
 * and PLAN 5.12 says the same event may never be applied twice. The identifier
 * is generated by the caller before the write, which is what makes a repeated
 * attempt recognisable as the same event rather than as a second one.
 *
 * The foreign key to the task is RESTRICT, so the history cannot be orphaned and
 * a task with a history cannot be erased out from under it. A deleted task is
 * deleted softly, which leaves both the task row and everything recorded about
 * it in place.
 *
 * [cardReference] and [stage] carry the optional detail PLAN 7.4 allows on a
 * card shortage — which card, and where it was noticed. They are stored as they
 * were typed and never made up: a shortage recorded as a bare number stays a
 * bare number.
 */
@Entity(
    tableName = "progress_events",
    foreignKeys = [
        ForeignKey(
            entity = TaskEntity::class,
            parentColumns = ["id"],
            childColumns = ["task_id"],
            onDelete = ForeignKey.RESTRICT,
            onUpdate = ForeignKey.RESTRICT,
        ),
    ],
    indices = [
        Index(value = ["task_id"]),
        Index(value = ["task_id", "kind"]),
    ],
)
data class ProgressEventEntity(
    @PrimaryKey
    @ColumnInfo(name = "id")
    val id: EntityId,
    @ColumnInfo(name = "task_id")
    val taskId: EntityId,
    @ColumnInfo(name = "kind")
    val kind: ProgressEventKind,
    /** How many pieces this movement was about; always more than none. */
    @ColumnInfo(name = "quantity")
    val quantity: Int,
    /** What the user wrote about it, or null when they wrote nothing. */
    @ColumnInfo(name = "note")
    val note: String? = null,
    /** The card's name or number, when the user gave one. */
    @ColumnInfo(name = "card_reference")
    val cardReference: String? = null,
    /** The pipeline step it was noticed at, when there is one. */
    @ColumnInfo(name = "stage")
    val stage: ProductionStage? = null,
    @ColumnInfo(name = "recorded_at")
    val recordedAt: Instant,
) {
    init {
        require(quantity > 0) {
            "A progress event has to be about at least one piece, was: $quantity"
        }
        require(note == null || note.isNotBlank()) {
            "A note is either something or absent, never blank."
        }
        require(cardReference == null || cardReference.isNotBlank()) {
            "A card reference is either something or absent, never blank."
        }
    }
}
