package dev.pnptracker.data.database

import androidx.room3.ColumnTypeConverters
import androidx.room3.ConstructedBy
import androidx.room3.Database
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import dev.pnptracker.data.database.converter.DatabaseConverters
import dev.pnptracker.data.database.dao.GameDao
import dev.pnptracker.data.database.dao.ItemDao
import dev.pnptracker.data.database.entity.GameEntity
import dev.pnptracker.data.database.entity.ItemEntity

@Database(
    entities = [GameEntity::class, ItemEntity::class],
    version = 1,
    exportSchema = true,
)
@ColumnTypeConverters(DatabaseConverters::class)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun gameDao(): GameDao

    abstract fun itemDao(): ItemDao
}

// The actual implementation is generated by the Room compiler for each target.
@Suppress("KotlinNoActualForExpect")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}
