package dev.pnptracker.data.database

import androidx.room3.ColumnTypeConverters
import androidx.room3.ConstructedBy
import androidx.room3.Database
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import dev.pnptracker.data.database.converter.DatabaseConverters
import dev.pnptracker.data.database.dao.CellSegmentDao
import dev.pnptracker.data.database.dao.ColorDao
import dev.pnptracker.data.database.dao.GameCellDao
import dev.pnptracker.data.database.dao.GameDao
import dev.pnptracker.data.database.dao.GameTableDao
import dev.pnptracker.data.database.dao.ImportDao
import dev.pnptracker.data.database.dao.TaskColorDao
import dev.pnptracker.data.database.dao.TaskDao
import dev.pnptracker.data.database.dao.TaskProgressDao
import dev.pnptracker.data.database.entity.CellSegmentEntity
import dev.pnptracker.data.database.entity.ColorAliasEntity
import dev.pnptracker.data.database.entity.ColorEntity
import dev.pnptracker.data.database.entity.DraftTaskEntity
import dev.pnptracker.data.database.entity.GameCellEntity
import dev.pnptracker.data.database.entity.GameEntity
import dev.pnptracker.data.database.entity.ImportBatchEntity
import dev.pnptracker.data.database.entity.ProgressEventEntity
import dev.pnptracker.data.database.entity.RawImportBlockEntity
import dev.pnptracker.data.database.entity.TaskColorEntity
import dev.pnptracker.data.database.entity.TaskEntity
import dev.pnptracker.data.database.entity.TaskStageEntity

@Database(
    entities = [
        GameEntity::class,
        GameCellEntity::class,
        CellSegmentEntity::class,
        ColorEntity::class,
        ColorAliasEntity::class,
        TaskEntity::class,
        TaskColorEntity::class,
        TaskStageEntity::class,
        ProgressEventEntity::class,
        ImportBatchEntity::class,
        RawImportBlockEntity::class,
        DraftTaskEntity::class,
    ],
    version = 5,
    exportSchema = true,
)
@ColumnTypeConverters(DatabaseConverters::class)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun gameDao(): GameDao

    abstract fun gameCellDao(): GameCellDao

    abstract fun cellSegmentDao(): CellSegmentDao

    abstract fun colorDao(): ColorDao

    abstract fun taskDao(): TaskDao

    abstract fun taskColorDao(): TaskColorDao

    abstract fun gameTableDao(): GameTableDao

    abstract fun taskProgressDao(): TaskProgressDao

    abstract fun importDao(): ImportDao
}

// The actual implementation is generated by the Room compiler for each target.
@Suppress("KotlinNoActualForExpect")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}
