package dev.pnptracker.data.database

import androidx.room3.ColumnTypeConverters
import androidx.room3.ConstructedBy
import androidx.room3.Database
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import dev.pnptracker.data.database.converter.DatabaseConverters
import dev.pnptracker.data.database.dao.ColorDao
import dev.pnptracker.data.database.dao.GameDao
import dev.pnptracker.data.database.dao.ItemDao
import dev.pnptracker.data.database.dao.TaskColorDao
import dev.pnptracker.data.database.dao.TaskDao
import dev.pnptracker.data.database.entity.ColorAliasEntity
import dev.pnptracker.data.database.entity.ColorEntity
import dev.pnptracker.data.database.entity.GameEntity
import dev.pnptracker.data.database.entity.ItemEntity
import dev.pnptracker.data.database.entity.TaskColorEntity
import dev.pnptracker.data.database.entity.TaskEntity

@Database(
    entities = [
        GameEntity::class,
        ItemEntity::class,
        ColorEntity::class,
        ColorAliasEntity::class,
        TaskEntity::class,
        TaskColorEntity::class,
    ],
    version = 2,
    exportSchema = true,
)
@ColumnTypeConverters(DatabaseConverters::class)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun gameDao(): GameDao

    abstract fun itemDao(): ItemDao

    abstract fun colorDao(): ColorDao

    abstract fun taskDao(): TaskDao

    abstract fun taskColorDao(): TaskColorDao
}

// The actual implementation is generated by the Room compiler for each target.
@Suppress("KotlinNoActualForExpect")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}
